In [1]:
library(data.table)
library(ggplot2)
library(openxlsx)

In [ ]:
project_dir <- <path to project>

In [5]:
cov_thrs <- list("human_cava_cohort_plasma_1" = 0.8, "human_cava_cohort_plasma_2" = 0.8, 
                 "human_bike_cohort_plasma_rerun" = 0.75, "human_bike_cohort_plaque_aorta_rerun" = 0.75)

In [7]:
full_summary_df <- data.table()
for(name_id in names(cov_thrs)){
    CORTHR = cov_thrs[name_id]

    summary_df <- fread(file.path(project_dir, name_id, "aggregated", "cv_comparison.csv"))

    summary_df[, status:="FAIL",]
    summary_df[summary_df$cor_coef > CORTHR, status:="PASS",]
    one_lib_failed <- unique(summary_df[status=="FAIL"]$sample_name)

    ## if one library failed, other also:
    summary_df[summary_df$sample_name %in% one_lib_failed,]$status <- "FAIL"
    summary_df <- unique(summary_df[, c("sample_name","cor_coef", "library", "status")])

    summary_df$run_id <- name_id

    full_summary_df <- rbind(summary_df, full_summary_df)
    
}

In [10]:
write.csv(full_summary_df, file.path(project_dir, "correlation_replicas.csv"))

In [13]:
full_summary_df[cor_coef > 0.75 & cor_coef < 0.8]

   sample_name cor_coef library status run_id
1  plaque_466  0.754    L2      PASS   human_bike_cohort_plaque_aorta_rerun
2  plaque_474  0.766    L2      PASS   human_bike_cohort_plaque_aorta_rerun
3  plaque_498  0.780    L1      FAIL   human_bike_cohort_plaque_aorta_rerun
4  plaque_506  0.789    L1      PASS   human_bike_cohort_plaque_aorta_rerun
5  plaque_506  0.773    L2      PASS   human_bike_cohort_plaque_aorta_rerun
6  plaque_509  0.790    L1      PASS   human_bike_cohort_plaque_aorta_rerun
7  plaque_511  0.791    L1      PASS   human_bike_cohort_plaque_aorta_rerun
8  plaque_513  0.792    L1      PASS   human_bike_cohort_plaque_aorta_rerun
9  plaque_522  0.790    L1      PASS   human_bike_cohort_plaque_aorta_rerun
10 plaque_524  0.786    L1      PASS   human_bike_cohort_plaque_aorta_rerun
11 462         0.790    L1      PASS   human_bike_cohort_plasma_rerun
12 586         0.786    L1      PASS   human_bike_cohort_plasma_rerun
13 15328_105   0.782    L2      FAIL   human_cava_cohort_plasma_2
14 15328_109   0.789    L1      FAIL   human_cava_cohort_plasma_2
15 15328_186   0.793    L2      FAIL   human_cava_cohort_plasma_2
16 15328_203   0.764    L1      FAIL   human_cava_cohort_plasma_2
17 15328_235   0.789    L1      FAIL   human_cava_cohort_plasma_2
18 15328_391   0.788    L2      FAIL   human_cava_cohort_plasma_2
19 15328_457   0.775    L2      FAIL   human_cava_cohort_plasma_2
20 15328_61    0.761    L2      FAIL   human_cava_cohort_plasma_2
21 15328_24    0.763    L1      FAIL   human_cava_cohort_plasma_1

In [14]:
full_summary_df[sample_name == "plaque_466"]

  sample_name cor_coef library status run_id
1 plaque_466  0.888    L1      PASS   human_bike_cohort_plaque_aorta_rerun
2 plaque_466  0.754    L2      PASS   human_bike_cohort_plaque_aorta_rerun